apiVersion: apps/v1
kind: Deployment
metadata:
  name: drive
  namespace: flask-drive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drive
  template:
    metadata:
      labels:
        app: drive
    spec:
      containers:
        - name: flask-drive
          image: flask-drive:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: drive
  namespace: flask-drive
spec:
  selector:
    app: drive
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP