apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: flask-drive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy-drive
          image: proxy-drive:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: flask-drive
spec:
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 #targetPort = port interne
  type: LoadBalancer